### ISSUE TITLE
报错-5

### ISSUE THREAD

**Issue by 800sea** [heiher/hev-socks5-tunnel#101]
作者大佬,你好  我在iOS上使用时,报错 -5,但是使用同样的文件描述符,badvpn-tun2socks 能够通过文件描述符获取到数据

**Comment by heiher** [comment]
返回值 `-5` 的话，应该是 tun fd 不对吧。打印出fd的值看看具体是多少呢？

**Comment by 800sea** [comment]
5。但是badvpn-tun2sock也是5 就能读取到数据了

**Comment by heiher** [comment]
配置文件和日志也贴出来看看吧。

**Comment by 800sea** [comment]
我先把issue关了。后面时间空一点在来调试

**Comment by Formerly** [comment]
同样报 5
NEPacketTunnelNetworkSettings 配置为:
```

let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "127.0.0.1")
settings.mtu = 8500
let ipv4Settings = NEIPv4Settings(addresses: ["198.18.0.20"], subnetMasks: ["255.255.255.0"])
ipv4Settings.includedRoutes = [NEIPv4Route.default()]
settings.ipv4Settings = ipv4Settings
let dns = NEDNSSettings(servers: ["8.8.8.8"])
settings.dnsSettings = dns
settings.proxySettings = nil
```

配置文件内容为
```
  let config = """
        tunnel:
          mtu: 8500

        socks5:
          port: 7890
          address: ::1
          udp: 'udp'

        misc:
          task-stack-size: 20480
          connect-timeout: 5000
          read-write-timeout: 60000
          log-level: debug
          limit-nofile: 65535
          log-file: \(logFilePath)
        """
```
最后表现结果为:
![WX20240123-114009@2x](https://github.com/heiher/hev-socks5-tunnel/assets/13330256/641a3a77-240d-480e-8868-53b6474f80b6)
