### ISSUE TITLE
pf route-to : very slow upload speed (less than 0.2 Mb/s)

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tunnel#107]
Download speed is ok (direct or via tun)
Upload speed to ip in chnroute is ok (direct)
Upload speed to the rest of ip very slow (through tun)

- hev conf

```yml
tunnel:
  name: utun
  mtu: 1500
  multi-queue: true
  ipv4: 198.18.0.1
  post-up-script: /opt/pf.tproxy/bin/up.sh
  pre-down-script: /opt/pf.tproxy/bin/down.sh
socks5:
  port: 1080
  address: 127.0.0.1
  udp: 'udp'
misc:
  limit-nofile: 655350
```

- pf conf

````
pass out quick on en0 inet proto tcp from any to TROJAN_SERVER_IP port = 443 flags S/SA keep state
pass out quick on en0 proto tcp from any to <direct> flags S/SA keep state
pass out quick on en0 proto udp from any to <direct> keep state
pass out on en0 route-to utun6 inet proto tcp all flags S/SA keep state
pass out on en0 route-to utun6 inet proto udp all keep state

````

## EDIT

**issue fixed by turning of tso** `sudo sysctl net.inet.tcp.tso=0`
