### ISSUE TITLE
DNS 如何工作？

### ISSUE THREAD

**Issue by Journalist-HK** [heiher/hev-socks5-tunnel#116]
[README.md](https://github.com/heiher/hev-socks5-tunnel/blob/master/README.md) 中并没有提及 DNS。按照[说明](https://github.com/heiher/hev-socks5-tunnel#linux)进行设置后不能正常解析 DNS，通过 IP 进行的连接可以正常被代理。

```
tunnel:
  name: tun0
  mtu: 8500
  multi-queue: false
  ipv4: 10.118.0.1
  ipv6: 'fdaf:052b:975c::1'

socks5:
  port: 7890
  address: 192.168.1.2
  udp: 'udp'
  mark: 438
```
