### ISSUE TITLE
OpenWrt 路由器上配置全局路由后无法连网

### ISSUE THREAD

**Issue by elzero** [heiher/hev-socks5-tunnel#139]
- 系统: OpenWrt 
- socks5: V2ray  服务正常 (浏览器配置路由器的socks5 能正常代理)
- 配置：
```yml
tunnel:
  name: tun0
  ipv4: 198.18.0.1
socks5:
  port: 10810
  address: 127.0.0.1
  udp: 'udp'
  mark: 0x438
```

执行以下脚本后整个路由器无法连网
```sh
ip rule add fwmark 0x438 lookup main pref 10

ip route add default dev tun0 table 20
ip rule add lookup 20 pref 20
```
