### ISSUE TITLE
Does this work with remote socks5 servers?

### ISSUE THREAD

**Issue by ameir** [heiher/hev-socks5-tunnel#167]
All of the examples I have seen show that the socks5 server is local to the tunnel client. In my case, I have a remote socks5 server that I would like to connect to.

I have tried this setup, and I might be able to get a few requests through the tunnel, but for the most part, requests hang, and I get the following in the client:
```
[2024-09-25 21:30:43] [I] 0x402f9048 io timeout
```
If I set the socks5 server in a browser directly, for example, it works just fine.

Below is my tunnel config:

```
# client
tunnel:
  name: hev0
  ipv4: 192.168.18.1

socks5:
  port: 1080
  address: xxxx
  udp: tcp
  mark: 438
misc:
 log-file: /tmp/hev.log
 log-level: debug
```

With each request, I can see (via tcpdump) the requests at the server side, but I am not sure why the requests don't seem to be making it back to the client correctly in most cases.
