### ISSUE TITLE
v2ray未能成功转发

### ISSUE THREAD

**Issue by dhp5** [heiher/hev-socks5-tunnel#168]
我的Tun2socks连接成功了。但是转发到v2ray服务器。解析出来的 全是EOF。请问这是什么问题呀？这是我服务端解析到的日志

[Info] common/mux: failed to read metadata > io: read/write on closed pipe
[Info] common/mux: failed to read metadata > io: read/write on closed pipe
[Info] [3411192088] transport/internet/udp: failed to handle UDP input > EOF
[Info] common/mux: failed to read metadata > io: read/write on closed pipe
[Info] [4159722323] transport/internet/udp: failed to handle UDP input > EOF
[Info] [1537859122] transport/internet/udp: failed to handle UDP input > EOF

这是我的配置：

```
       tunnel:
            mtu: 8500
        
        socks5:
            port: 10808
            address: 127.0.0.1
            udp: 'udp'
        
        misc:
            task-stack-size: 81920
            connect-timeout: 5000
            read-write-timeout: 60000
            log-file: stderr
            log-level: debug
            limit-nofile: 65535
```

```
func getNetworkSettings(with mtu: Int) -> NEPacketTunnelNetworkSettings {
        let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "254.1.1.1")
        settings.mtu = NSNumber(integerLiteral: mtu)
        settings.ipv4Settings = {
            let settings = NEIPv4Settings(addresses: ["198.18.0.1"], subnetMasks: ["255.255.255.0"])
            settings.includedRoutes = [NEIPv4Route.default()]
            return settings
        }()
        settings.ipv6Settings = {
            let settings = NEIPv6Settings(addresses: ["da26:2626::1"], networkPrefixLengths: [126])
            settings.includedRoutes = [NEIPv6Route.default()]
            return settings
        }()
        
        settings.dnsSettings = NEDNSSettings(servers: ["1.1.1.1", "8.8.8.8"])
        return settings
    }
```
