### ISSUE TITLE
可否DNS转发

### ISSUE THREAD

**Issue by 250king** [heiher/hev-socks5-tunnel#186]
最近一直也在研究如何将贵项目的Tun2socks与V2ray或者其他代理库使用。其中也碰到了一个问题，就是在BadVPN的Tun2socks里面有以下参数
https://github.com/2dust/v2rayNG/blob/1b2cc11a9716c7afad3f2bf5d84b113c0941c51a/V2rayNG/app/src/main/java/com/v2ray/ang/service/V2RayVpnService.kt#L228
请问贵项目支持吗？我觉得这一点比较重要，因为只有这个支持的才能实现DNS分流

**Comment by 250king** [comment]
但我现在已经addDnsServer到26.26.26.2（tun地址）会导致无法上网。如果设置1.1.1.1没问题但也没法指使设备使用v2ray dns了

**Comment by HeXis-YS** [comment]
badvpn tun2socks可以把DNS请求转发至一个单独的dokodemo入站端口（dns-in），V2ray/Xray通过路由规则把这个端口的流量转发至一个DNS出站。
这一步操作也可以在代理软件内部执行，唯一的区别就是就是刚才从dns-in进入的流量现在全部从socks端口进入了。路由配置稍微改一下，把socks端口进入的，目标端口为53的流量分离出来转发至DNS出站即可。
两种方式没有本质区别。

**Comment by 250king** [comment]
你意思是？那我的addDnsServer应该是？
```
val builder = Builder()
        builder.setMtu(1500)
        builder.addAddress("26.26.26.1", 30)
        builder.addRoute("0.0.0.0", 0)
        builder.addDnsServer("1.1.1.1")
```
还是说在配置文件弄东西？
```
socks5:
  port: 10808
  address: 127.0.0.1
  udp: 'udp'

misc:
  log-level: info

tunnel:
  name: tun0
  mtu: 1500
  ipv4: 26.26.26.2
```
