### ISSUE TITLE
openwrt 中 ping 不通，但是能 ssh 连通并登录，很奇怪

### ISSUE THREAD

**Issue by ztj1993** [heiher/hev-socks5-tunnel#190]
使用的是最新的发布版本：
```
root@LU:~# ./hev-socks5-tunnel-linux-mips32elsf --version
./hev-socks5-tunnel-linux-mips32elsf CONFIG_PATH
Version: 2.7.5 5a896c2
```

使用了下面的配置：
```
tunnel:
  name: ahy
  mtu: 8500
  multi-queue: true
  ipv4: 192.168.110.0

socks5:
  port: 1080
  address: ***
  udp: udp
  username: ***
  password: ***

misc:
  log-level: debug
```
注：tcp, mtu, multi-queue, ipv4 等都修改测试了，就是不行。

执行下面了路由命令：
```
ip route add 192.168.110.0/24 dev ahy
```

可以确认的是目标主机是允许 ping 的。
然后执行了 `ping 192.168.110.1`，日志没有任何的输出，但是执行 `ssh root@192.168.110.1`，日志输出正常且正常登录。
即使 ping 指定网卡实例也不行，没有任何的输出，请问这种情况大家遇到过吗，如何解决？
