### ISSUE TITLE
iOS VPN crash with chrome browser

### ISSUE THREAD

**Issue by GitPingPong** [heiher/hev-socks5-tunnel#203]
```
tunnel:
    mtu: 1500
    multi-queue: true
    ipv4: "198.18.0.1"
    ipv6: "fc00::1"
socks5:
    port: 38482
    address: "xx.xx.xx.xx"
    udp: "udp"
misc:
  # task stack size (bytes)
  task-stack-size: 21504 # 20480 + tcp-buffer-size
  # tcp buffer size (bytes)
  tcp-buffer-size: 1024
```
This is my config, I don't know how to debug it.

After browsing some pages, there is a high chance that the VPN will crash.
