### ISSUE TITLE
Bug 报告：FreeBSD 平台下配置 tun 接口时生成错误的点对点地址

### ISSUE THREAD

**Issue by Solvris** [heiher/hev-socks5-tunnel#237]
### 📌 概要

在 FreeBSD 平台上使用配置文件创建 tun 接口时，程序自动配置了本地地址和远端地址相同的 IP 地址（例如 `198.18.0.1 --> 198.18.0.1`），导致无法正常使用。期望支持通过 CIDR 或双地址格式来设置 tun 接口。

---

### 🧾 环境信息

- **系统**: FreeBSD 14.2-RELEASE 
- **配置文件**:
```yaml
tunnel:
  # Interface name
  name: tun0
  # Interface MTU
  mtu: 1500
  # Multi-queue
  multi-queue: true
  # IPv4 address
  ipv4: 198.18.0.1
  # IPv6 address
#  ipv6: 'fc00::1'
```

---

### 📋 当前行为

执行命令查看接口状态：

```bash
ifconfig tun0
```

输出如下：

```
tun0: flags=1008051<UP,POINTOPOINT,RUNNING,MULTICAST,LOWER_UP> metric 0 mtu 1500
        options=80000<LINKSTATE>
        inet 198.18.0.1 --> 198.18.0.1 netmask 0xffffffff
        groups: tun
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        Opened by PID 2168
```

此时 tun 接口被配置为 point-to-point 模式，并且本地地址与远端地址相同，这会导致：

- 网络通信失败；
- 无法正常添加路由；
- 程序可能因网络不通而卡住或崩溃；

---

### ✅ 预期行为

- 支持通过配置文件指定 CIDR 格式（如 `198.18.0.1/30`）；
- 或者支持指定一对地址（如 `local_ip` + `remote_ip`）；
- 从而正确初始化 tun 接口，使其能正常参与网络通信。

---

#### 方案一：支持 CIDR 格式配置

更新配置文件字段定义：

```yaml
tunnel:
  name: tun0
  mtu: 1500
  ipv4: 198.18.0.1/30
```

程序内部应调用类似以下命令：

```bash
sudo ifconfig tun0 198.18.0.1/30 up
```

#### 方案二：支持双地址配置

允许用户分别指定本地和远程地址：

```yaml
tunnel:
  name: tun0
  mtu: 1500
  ipv4:
    local: 198.18.0.1
    remote: 198.18.0.2
```

程序内部应调用类似以下命令：

```bash
sudo ifconfig tun0 198.18.0.1 198.18.0.2 up
```

---
