### ISSUE TITLE
Cant use in public socks ip address

### ISSUE THREAD

**Issue by AhmadNemati** [heiher/hev-socks5-tunnel#35]
i want to use your project for public socks ip
so i just copy and paste command it seems i have some problem 

my public ip address is 5.78.92.184:1080

my config:

```
tunnel:
  # Interface name
  name: tun0
  # Interface MTU
  mtu: 8500
  # Multi-queue
  multi-queue: false
  # IPv4 address
  ipv4: 198.18.0.1
  # IPv6 address
  ipv6: 'fc00::1'

socks5:
  
  port: 1080
  address: 5.78.92.184
  udp: 'tcp'
```

and last 
sudo ip route add 5.78.92.184 dev eth0 metric 10
sudo ip route add default dev tun0 metric 20

but have problem and i cant do ping or curl or ... 
what should i do?
