### ISSUE TITLE
Linux  hev_socks5_tunnel_main(config_path, 1); stoping thread and not starting

### ISSUE THREAD

**Issue by tozik** [heiher/hev-socks5-tunnel#41]
```
#include "hev-socks5-tunnel.h"
....
int ret = hev_socks5_tunnel_main(config_path, 1);
....
```

hev using like library (using your release libs or build by myself behavior is the same)
If path to config is wrong method returning -1

Config is
```
tunnel:
  # Interface MTU
  mtu: 8500
  
socks5:
  #Socks5 server port
  port: **port**
  #Socks5 server address (ipv4/ipv6)
  address: **ip**
  #Socks5 UDP relay mode (tcp|udp)
  udp: 'tcp'
  #Socks5 server username
  username: 'user'
  #Socks5 server password  
  password: 'pass'

misc:
   # task stack size (bytes)
  task-stack-size: 20480
   # connect timeout (ms)
  connect-timeout: 5000
   # read-write timeout (ms)
  read-write-timeout: 60000
   # stdout, stderr or file-path
  log-file: stderr
  log-level: trace

   # If present, set rlimit nofile; else use default value
  limit-nofile: 65535
```

working if runing with terminal your release, if build on local machine, and run from terminal, its dropping/stopping from time to time

could you advise something?
