### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by H-Khoujani** [heiher/hev-socks5-tunnel#46]
in the readme section `Run` said set DEFAULT_IFACE
what is it and how to set it ?

my linux -> `ip route` command:
default via 192.168.1.1 dev wlp0s20f3 proto dhcp metric 600 
169.254.0.0/16 dev wlp0s20f3 scope link metric 1000 
192.168.1.0/24 dev wlp0s20f3 proto kernel scope link src 192.168.1.6 metric 600

my tunnel Config: 
tunnel:
  name: tun0
  mtu: 9000
  multi-queue: false
  ipv4: 198.18.0.1
socks5:
  port: 10801
  address: 127.0.0.1
  udp: 'udp'
misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: stderr
  log-level: debug
  limit-nofile: 65535
  
  I starting xray core after tunnel on server 127.0.0.1 and port 10801 
  but it show me a loop of message:
  
  [2023-06-27 13:32:18] [D] 0x55d40bb18b90 socks5 session tcp destruct
[2023-06-27 13:32:18] [D] 0x55d40bb18b90 socks5 client tcp destruct
[2023-06-27 13:32:18] [D] 0x55d40bb18b90 socks5 client destruct
[2023-06-27 13:32:18] [D] 0x55d40bb18b90 socks5 destruct
[2023-06-27 13:32:18] [I] 0x55d40bb193d0 io timeout
[2023-06-27 13:32:18] [D] 0x55d40bb193d0 socks5 session tcp destruct
[2023-06-27 13:32:18] [D] 0x55d40bb193d0 socks5 client tcp destruct
[2023-06-27 13:32:18] [D] 0x55d40bb193d0 socks5 client destruct
[2023-06-27 13:32:18] [D] 0x55d40bb193d0 socks5 destruct

**Comment by mrgharabaghi** [comment]
Did you bypass your upstream SOCKS5 server?
Take a look at this:
https://github.com/heiher/hev-socks5-tunnel#run

For example, this is you Xray server IP: `55.66.77.88`
And this is your PC default interface name: `eth0`
```sh
# Bypass upstream socks5 server
sudo ip route add 55.66.77.88 dev eth0 metric 10

# Route others
sudo ip route add default dev tun0 metric 20
sudo ip -6 route add default dev tun0 metric 20
```
```yml
tunnel:
  name: tun0
  mtu: 8500
  multi-queue: false
  ipv4: 198.18.0.1
  ipv6: 'fc00::1'

socks5:
  port: 800
  address: 127.0.0.1
  udp: 'udp'

misc:
  #  task-stack-size: 20480
  #  connect-timeout: 5000
  #  read-write-timeout: 60000
  log-file: stderr
  log-level: info
  pid-file: ./hev-socks5-tunnel.pid
  #  limit-nofile: 65535
```
