### ISSUE TITLE
在ios上刷抖音会crash

### ISSUE THREAD

**Issue by Yewenyu** [heiher/hev-socks5-tunnel#74]
使用这个tun2socks之后，刷其他视频app正常，比如腾讯和爱奇艺，但是刷抖音一段时间后会crash

我用的clash库，不过自行修改了限制最大连接数，达到一定连接数后就会强制关闭比较旧的连接。

不是ios内存限制崩溃。

我用其他tun2socks是正常的。

可是其他tun2socks的速度比这个慢很多。

麻烦您修一修这个bug

```
tunnel:
  mtu: 8500

socks5:
  port: 7890
  address: ::1
  udp: 'udp'
```
