### ISSUE TITLE
iOS networkextension  hev_socks5_tunnel_main  always returns -1

### ISSUE THREAD

**Issue by 800sea** [heiher/hev-socks5-tunnel#81]
xcode 15.0.1 
我在ios 的networkextension 中使用hev-socks5-tunnel 永远返回: **-1**   在mac端使用同样的配置能正常启动
```
func srart(){
        let localConfigFileURL = Bundle.main.url(forResource: "Config", withExtension: "yml")
        let a = try? String(contentsOf: localConfigFileURL!)
        printLog("VPN的值-\(a!)")
        
        let fb = tunnelFileDescriptor()
        printLog("VPN的值文件描述-\(localConfigFileURL!.relativePath)")  // fb is 5
      
        let cStringPointer = localConfigFileURL!.relativePath.utf8CString.withUnsafeBufferPointer {
            // $0.baseAddress 是指向 C 字符串数组的 UnsafePointer<CChar>
            return $0.baseAddress
        }
        
        let code = hev_socks5_tunnel_main(cStringPointer, fb!)
        printLog("VPN的tun2socks返回状态-  \(code)")
}
```
Config.yml :
```
tunnel:
  name: tun0
  mtu: 8500
  multi-queue: false
  ipv4: 198.18.0.1
  ipv6: 'fc00::1'
  
socks5:
  port: 7890
  address: 127.0.0.1
  udp: 'udp'
```
