### ISSUE TITLE
代理成功后 app能够正常访问,浏览器不行

### ISSUE THREAD

**Issue by 800sea** [heiher/hev-socks5-tunnel#82]
我在iOS上使用的模式是 NetworkExtension ->hev-socks5-tunnel->shadowsocks-rust 来实现代理.但是我成功过运行后,正常app能过访问,浏览器不行.我考虑是否是DNS的原因. 或者是我的配置有问题?
我的 NetworkExtension的配置
```
func config()->NEPacketTunnelNetworkSettings{
        let tunSet = NEPacketTunnelNetworkSettings.init(tunnelRemoteAddress: "240.0.0.1")
        tunSet.mtu = 1500
        tunSet.ipv4Settings = NEIPv4Settings.init(addresses: ["198.18.0.1"], subnetMasks: ["255.255.255.0"])
        tunSet.ipv4Settings?.includedRoutes = [NEIPv4Route.default()]
        tunSet.dnsSettings = NEDNSSettings(servers: ["8.8.8.8"])//"26.26.26.53","114.114.114.114",
        return tunSet
    }
```
我的hev-socks5-tunnel配置
```
tunnel:
  name: tun0
  mtu: 1500
  multi-queue: false
  ipv4: 198.18.0.1
  ipv6: 'fc00::1'
  
socks5:
  port: 7890
  address: 127.0.0.1
  udp: 'udp'

```

我的shadowsocks启动配置
```
let cmd = #"sslocal -b 127.0.0.1:7890 -s 172.14.16.136:8388 -m aes-256-gcm -k dsewsa"#
```
我的shadowsocks只启动了socks5没有启动tun.不知道是否有影响
