### ISSUE TITLE
OpenWRT下运行socks5透明代理失败

### ISSUE THREAD

**Issue by weber110** [heiher/hev-socks5-tunnel#90]
启动方式：
./hev-socks5-tunnel-linux-arm64 socks5.yml

配置如下：
```yaml
tunnel:
  # Interface name
  name: tun0
  # Interface MTU
  mtu: 8500
  # Multi-queue
  multi-queue: false
  # IPv4 address
  ipv4: 10.168.0.1
  # IPv6 address
  ipv6: 'fc00::1'

socks5:
  # Socks5 server port
  port: 30001
  # Socks5 server address (ipv4/ipv6)
  address: node.example.com
  # Socks5 UDP relay mode (tcp|udp)
  udp: 'udp'
  # Socks5 server username
  #username: 'myuid'
  # Socks5 server password
  #password: 'mypwd'
  # Socket mark
  mark: 438
```

问题现象：
运行后控制台打印日志：[2023-12-28 03:07:32] [E] socks5 tunnel open，然后就中断了
ip addr也未见tun0接口被自动创建
